### ISSUE TITLE
Feature: Support for NATS storage

### ISSUE THREAD

**Issue by adpande** [spirit-labs/tektite#120]
Hi,

It would be awesome if we provide compatibility with NATS objext storage along with S3 and MinIO.

Here is the documentation: https://docs.nats.io/using-nats/developer/develop_jetstream/object

Regards,
Abhishek

**Comment by devguyio** [comment]
> Hi,
> 
> It would be awesome if we provide compatibility with NATS objext storage along with S3 and MinIO.
> 
> Here is the documentation: https://docs.nats.io/using-nats/developer/develop_jetstream/object
> 
> Regards, Abhishek

Thanks for your suggestion. Would you mind sharing more details about the use case? I'm pretty familiar with NATS and JetStearms and as you know, the main use case of JetStreams (since you've mentioned object storage) is providing a messaging system with at-least-once delivery guarantees, while S3 and MinIO are primarily object stores. 

So since JetStreams isn't primarily an object store, but a messaging system, I'd expect that the introduction of Tektite would be to replace JetStreams. Or at least complement it without relying on JetStreams as an object store.

Sharing more details about the use case, the requirements, the problem etc would be super helpful.

**Comment by adpande** [comment]
Hi @devguyio ,

Thinking out load here:

I agree Jetstream is not a primary use case or nats but it does provides Object/file storage. I have given the link above. We are using NATS internally and like to store the tektite data to it instead of MinIO. 

We can also add feature to consume messages from NATS stream directly. 

Hope this helps.

Regards,
Abhishek

**Comment by purplefox** [comment]
I agree with @devguyio that this is not of primary importance. However, the Tektite object store has a very simple API, so if you want to implement it yourself, it would be a nice contribution to the project :)

**Comment by purplefox** [comment]
I'm going to close this as not on the roadmap for now.
