### ISSUE TITLE
Review versions of Kafka APIs that we support

### ISSUE THREAD

**Issue by purplefox** [spirit-labs/tektite#193]
We currently advertise support of fairly low versions of the Kafka APIs that we support, as these were the simplest to support before we had Kafka protocol generation.

Now that we have generation we should consider upping the versions to the more recent versions.

We should also look into returning broker supported features in ApiVersionsResponse.

**Comment by r2munz** [comment]
@purplefox:
@devguyio and I recently discussed the possibility of having myself assigned to this issue. I would be more than happy to contribute.
As a general strategy, I would like to propose to include a comprehensive review of the currently supported Kafka API inside our documentation and use it as a starting point to make individual reviews on the single API Keys, spawning individual issues for each of them to implement new versions, where needed.
In order to have new versions implemented, Slack could be serving as a central venue for discussion, where you could provide thoughts, reasoning and suggestion about the whys and maybe the hows of the new implementations.
Let me know your thoughts around it, I am looking forward to hear from you!
